name: Commit & Push ðŸš€

on:
  workflow_run:
    workflows: ["Publish ðŸ“"]
    types: [completed]

jobs:
  commit-push:
    name: Commit Changes & Push
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Extract Tag Name
      run: echo "TAG_NUMBER=$(git describe --tags | sed 's/v//')" >> $GITHUB_ENV
    - name: Commit Changes
      uses: EndBug/add-and-commit@v9
      with:
        add: "-A"
        author_name: "github-actions[bot]"
        author_email: "github-actions[bot]@github.com"
        default_author: github_actions
        fetch: true
        message: "chore: bump up $TAG_NUMBER version from workflow" 
    - name: Push changes
      run: git push